### ISSUE TITLE
Fakefile should be dev dependency?

### ISSUE THREAD

**Issue by adambro** [kvz/fakefile#2]
If I read the `install.js` correctly it just copies the `Makefile` and validates it. Is there any reason to drag `fakefile` and its dependencies into production code?

**Comment by kvz** [comment]
I guess the only reason is if you're going to make automation rely on the produced Makefile, but I strongly recommend against that, so, no : )

**Comment by kvz** [comment]
Ah, I updated the readme with `--save-dev` to better reflect that, do you think it's okay like this?

**Comment by adambro** [comment]
Yeah, that's exactly what I wanted. Thanks.
