### ISSUE TITLE
Commands that contain '-' (hyphen) don't work

### ISSUE THREAD

**Issue by sparcbr** [kvz/fakefile#7]
Problem:

Commands with hyphen doesn't work, because the hyphen is erroneously converted to ':'.

In my package.json I have:
```
"scripts": {
	"check-outdated": "check-outdated --ignore-pre-releases",
...
```
Let's run:
```
❯ make check-outdated
npm run check:outdated
npm ERR! missing script: check:outdated
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     check-outdated
```

Solution: we can use some other character.. some options:
¬ / =

**Comment by kvz** [comment]
This is a known issue and a bit of a headache but I’m running into limitations of my Makefile-fu :) and not really liking those chars as workarounds 🤔

**Comment by Jarvie8176** [comment]
https://gist.github.com/kvz/79554af7f2d1b1379536#gistcomment-3491009 maybe?

**Comment by kvz** [comment]
Thanks, adding this in 1.0!

**Comment by kvz** [comment]
`+ fakefile@1.0.0`
